<a href="https://colab.research.google.com/github/aparn0168/CALAB/blob/main/Chap4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Chap.4 numpy套件(numeric python)
##為什麼需要numpy?
#####numpy由c撰寫，速度快python 10~1000倍以上
#####numpy儲存結果較正確，python數字儲存不正確
#####numpy節省記憶體儲存空間
#####numpy的向量(矩陣計算)速度快
#####numpy的取值方便

In [ ]:
a_list=[1,2,3,4,5] #做一個List
print(a_list*3)#list內容印三次

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:

#numpy套件的ndarray型態,提供element-wise的操作
import numpy as np #用numpy 名稱用np簡寫
a=np.array([1,2,3,4,5])#存資料進a(numpy)
print(a*3)#內容*3印出

[ 3  6  9 12 15]


In [ ]:
a=np.array([1,2,3,4,5])#存資料進a(numpy)
print(type(a))
print(a.shape) #ndaary的形狀
print(a.dtype) #資料的型態
print(a.ndim) #維度

<class 'numpy.ndarray'>
(5,)
int64
1


In [ ]:
import numpy as np#用numpy 名稱用np簡寫
z=np.zeros(6)#存6個0進z(numpy)
print(z)#印Z的內容
print(np.empty((2,3,4)))#存空值印出來(3*4)*2個
print(np.arange(10))#存範圍(0-9)印出來

[0. 0. 0. 0. 0. 0.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a=np.zeros(10)
print(a)
print(a.ndim) #1維List 1*10
b=a.reshape(2,5) #改變A的微度為2*5
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#ndarray的進階操作

In [ ]:
my_array=np.arange(10)#存範圍(0-9)
print(my_array)#印my_array
print(my_array[0])#印my_array第0項
print(my_array[0:5])#印my_array到第5項

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


###2維資料取值

In [ ]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])#存範圍 5*2 的二維資料 (0-4)(5-9)
print(my_2d_array)#印my_2d_array
print(my_2d_array[1,:])#印my_2d_array第一排
print(my_2d_array[:,1])#印my_2d_array不管哪一排的第1個
print(my_2d_array[1,1])#印第一排第一個

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [ ]:
my_array=np.arange(0,10)#存範圍(0-9)
print(my_array)#印my_array
print(my_array.shape)#印my_array的大小
my_2d_array=my_array.reshape(2,5)#把微度改2微 存範圍 5*2 的二維資料 
print(my_2d_array)#印my_2d_array
print((np.arange(0,100).reshape(10,10)))#印 範圍0-99 10*10

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


#numpy的空值nan

In [ ]:

b=np.array([56, 8, 19, 14, np.nan])#存資料進b(numpy) numpy.nan空值
print(b)#印b

[56.  8. 19. 14. nan]
